### ISSUE TITLE
Credentials needed for usgs-wim-fws-cbrs AWS subaccount

### ISSUE THREAD

**Issue by ltmetz** [USGS-WiM/CBRS-projects-map#101]
Can I please have credentials/access to log into usgs-wim-fws-cbrs subaccount?

**Comment by lprivette** [comment]
Paul has requested some changes to the print map template and Lorraine needs to be able to log on to the console to turn on the bastion

**Comment by aaronstephenson** [comment]
Done. Sent via email.

**Comment by ltmetz** [comment]
Hi! I was able to log into the subaccount, however I cannot see any instances. 

![image](https://user-images.githubusercontent.com/49204642/160156095-26eccc29-d1c1-4021-bea6-bb2997be38f6.png)

Am I doing something wrong here??

**Comment by aaronstephenson** [comment]
Did you set up your MFA in that subaccount?

**Comment by ltmetz** [comment]
Nope! I just set it up. Logged out then back it and they are showing up now. Sorry! And thank you!
