### ISSUE TITLE
Restrict access to test site hosted in S3

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/CBRS-projects-map#46]
https://test.wim.usgs.gov/cbrs-projects/

**Comment by HansVraga** [comment]
To clarify -  we need to restrict access to this site to DoI network only.

**Comment by aaronstephenson** [comment]
This was a tricky one (once again, the AWS documentation and policies are inconsistent), but I think I got it. Let me know.

**Comment by HansVraga** [comment]
Lauren and I Testing this morning, couldn't connect to:
https://test.wim.usgs.gov/cbrs-projects/

From off-network, VPN, or on-network. We get the WiM error screen.

I also had a chat going with one of the FWS CBRS folks (Dana) - she at 164.159.59.2 and had the same experience - the "WiM - error" screen.

**Comment by aaronstephenson** [comment]
OK, I figured out that the bucket policy restrictions for this bucket aren't working because we're sending traffic through Luigi first, as a proxy. We should discuss this @HansVraga .

**Comment by aaronstephenson** [comment]
This is implemented. We created a new bucket (test-internal.wim.usgs.gov) and have it proxied through Apache on Luigi, where it is restricted by IP addresses.

**Comment by HansVraga** [comment]
I pulled the trigger too early. Dana and another tester at FWS can't access the page.

**Comment by HansVraga** [comment]
@aaronstephenson can you verify the IP address range you've allowed through Luigi is what we have for the full range of DoI addresses? Does it include the IP address above where Dana tested earlier?

**Comment by aaronstephenson** [comment]
I added 164.159.0.0/16 to the Apache config. The list I'm working from is at https://docs.google.com/document/d/1sJeEHJJnJsT8H7_hXxy9_XUeC2-LrKYZlV9TVpNP5_Y/edit
