### ISSUE TITLE
Unable to access aws account, mfa not working

### ISSUE THREAD

**Issue by ltmetz** [USGS-WiM/CBRS-projects-map#83]
Hi Aaron, so I am trying to log into AWS and I have my IAM user name, my password and authy setup, but it keeps telling me that my authentication information in incorrect. Do you have any insight into this??

P.s. I messaged you this and so you can ignore that...

**Comment by aaronstephenson** [comment]
Looks like you haven't logged in for almost a year, it could be that it is expired. I'll reset it and send you the new one.

**Comment by aaronstephenson** [comment]
Turns out the problem was that your IAM Access Key had been removed. I don't think any WIM personnel would have done that, so I suspect it was our AWS vendor.

Anyway, the solution was to create a new key pair, remove the current virtual MFA device, and set up a new virtual MFA device.
