### ISSUE TITLE
Give Lauren access to cbrsgis.wim.usgs.gov 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/CBRS-projects-map#96]
And Chad too but I think he already has access by now?

**Comment by fanguyc-usgs** [comment]
Created IAM account and put in Administrator and Force_MFA.

@aaronstephenson I need to confirm with you if we need to do anything else for permissions since Lauren can't see the EC2 instances atm.

**Comment by aaronstephenson** [comment]
We should revisit permissions for this entire sub-account. For years it was just me doing work in there, so the Administrator group was enough. Then Katrine needed access but wasn't sure what specific permissions she needed (and she only needed to work in there once or twice per year), so I just added her to the Administrator group also, along with the usual Spiderman Responsibility chat. But now that more people will seemingly need access, we should return to our usual Principle of Least Permissions, and create groups and policies that give these users only the exact access they need.

**Comment by aaronstephenson** [comment]
By "see" do you mean for example that nothing appears in the AWS web console for EC2, or that she can't RDP onto the instances, or something else? If she's an Administrator there should be no problem with the web console. For RDP, access should only be via the bastion server (which must be booted up before use), not directly from her laptop to the AGS instance, and her IP address should be added to the bastion's security group for port 3389 ("sg-0bd78714604aa182c (rdp-whitelist-to-mgmt)").

**Comment by fanguyc-usgs** [comment]
When viewing EC2 instances, it looked blank/empty for her account when logged in, so I think there might have been some weird permission issue with viewing EC2.

**Comment by aaronstephenson** [comment]
OK, I'll take a look.

**Comment by aaronstephenson** [comment]
Yeah, weird, the Administrator permissions are dead simple, and don't conflict with the MFA group permissions. I'll chat with Lauren directly.
